### PR TITLE
msdkenc: remove internal vpp function

### PR DESCRIPTION
**Pull request by liuyinhangx**
The internal vpp function and msdkvpp plugin are duplicated, so remove the internal vpp, please use msdkvpp plugin to do conversion if necessary.

### CODE REVIEW

**Comment by liuyinhangx** [comment]
@mengker33 @HeJunyan @xhaihao @xuguangxin @tong1wu please help to review, thanks.

**Comment by liuyinhangx** [comment]
No comments, close this PR.

**Comment by xuguangxin** [comment]
@mengker33 , @HeJunyan  could you help review this patch?
thank you

**Comment by mengker33** [comment]
@liuyinhangx, I remembered your previous PR also removed the unsupported formats, but I don't see anything here. I guess it is because of the dynamic caps patch. The thing is if we cannot check-in dynamic caps patch soon, then the caps info still shows these unsupported formats, and users might fail to run with these formats (i.e. I420, RGB...) without any warning/error log.

**Comment by liuyinhangx** [comment]
Static caps certainly cannot fully resolve the different formats supported on different platforms.
Even if individual image formats are removed, other platforms will have unsupported formats.
In the encoding initialization phase, if there is an unsupported format, an error will also be reported.
In addition, CI will also cover most of the test cases.
So creating a patch to delete the individual formats feels meaningless.

**Comment by mengker33** [comment]
> Static caps certainly cannot fully resolve the different formats supported on different platforms. Even if individual image formats are removed, other platforms will have unsupported formats. In the encoding initialization phase, if there is an unsupported format, an error will also be reported. In addition, CI will also cover most of the test cases. So creating a patch to delete the individual formats feels meaningless.

Hi Yinhang, my concern is that users usually check the caps to know if a format is supported, if we remove internal vpp while don't modify caps in the meantime, it might confuse them. And the error/warning log is from msdk/vpl level, something like mfx_query failed, and they may have no idea why the query failed.
Anyway, let's see Haihao's comment about [MR](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4000) you sent to upstream.

**Pull request closed without merging**
