### PR TITLE
msdk: Add dynamic capabilities support

### PR DESCRIPTION
**Pull request by liuyinhangx**

### CODE REVIEW

**Comment by liuyinhangx** [comment]
CI passed, close this PR.

**Comment by liuyinhangx** [comment]
CI passed, close this PR.

**Comment by uartie** [comment]
@liuyinhangx unfortunately these patches cause no msdk elements to be registered with gst-libvpl on legacy platforms (legacy uses msdk runtime).  This is a huge gap with our CI pre-check because it causes all of the cases to be skipped instead of fail... and therefore the test run is reported as a success ☹️  

https://media-ci.ostc.intel.com/build/850426

Since these patches are merged upstream it needs to be fixed ASAP.  I will file a bug there.

**Comment by uartie** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2506

**Pull request closed without merging**
